[tools]
bat = "latest"
fd = "latest"
delta = "latest"
dive = "latest"
fzf = "latest"
gcloud = "latest"
ghq = "latest"
gitui = "latest"
go = "latest"
gojq = "latest"
grex = "latest"
hadolint = "latest"
jnv = "latest"
killport = "latest"
lefthook = "latest"
lsd = "latest"
node = "24"
pnpm = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
stern = "latest"
terraform = "latest"
tflint = "latest"
trivy = "latest"
typos = "latest"
uv = "latest"

"github:bensadeh/tailspin" = "latest"
"github:k1LoW/git-wt" = "latest"
"github:wfxr/csview" = "latest"
