---
homebrew_taps:
  - datawire/blackbird
  - derailed/k9s
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core
  - nektos/tap

homebrew_packages:
  - act
  - ansible
  - anyenv
  - aria2
  - atool
  - awscli
  - azure-cli
  - bat
  - binutils
  - binwalk
  - cmake
  - cmigemo
  - coreutils
  - ctags
  - curl
  - fd
  - ffmpeg
  - findutils
  - fontconfig
  - fontforge
  - foremost
  - gcc
  - gdb
  - ghq
  - git
  - go
  - graphviz
  - grpcurl
  - hadolint
  - helm
  - htop
  - httpie
  - imagemagick
  - iproute2mac
  - jq
  - jsonlint
  - k9s
  - kind
  - kubectx
  - kubernetes-cli
  - lsof
  - luajit
  - lv
  - mosh
  - neovim
  - netcat
  - nkf
  - nmap
  - node
  - packer
  - parallel
  - peco
  - pigz
  - prettier
  - pv
  - python
  - readline
  - ripgrep
  - rsync
  - shellcheck
  - shfmt
  - socat
  - sqlite
  - stern
  - sysdig
  - telepresence
  - telnet
  - terraform
  - terraformer
  - tflint
  - the_silver_searcher
  - tmux
  - tree
  - unar
  - watch
  - wget
  - xz
  - yamllint
  - yapf
  - yq
  - zsh
  - zstd

homebrew_cask_apps:
  - "0xed"
  - alfred
  - appcleaner
  - balenaetcher
  - deepl
  - disablemonitor
  - docker
  - font-noto-sans-cjk-jp
  - font-noto-serif-cjk-jp
  - google-chrome
  - google-cloud-sdk
  - google-japanese-ime
  - iterm2
  - karabiner-elements
  - mailspring
  - multipass
  - ngrok
  - odrive
  - osxfuse
  - parallels-client
  - slack
  - visual-studio-code
  - wireshark
  - zoomus
